# Generated by Django 5.1.3 on 2024-12-02 23:03

import django.contrib.auth.models
import django.utils.timezone
import users.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Почта"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        default="Не указано",
                        max_length=35,
                        null=True,
                        verbose_name="Телефон",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True,
                        default="Не указано",
                        max_length=150,
                        null=True,
                        verbose_name="Имя",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True,
                        default="Не указано",
                        max_length=150,
                        null=True,
                        verbose_name="Фамилия",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        default="non_avatar.png",
                        null=True,
                        upload_to=users.models.upload_for_users,
                        verbose_name="Аватар",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        default="Не указано",
                        max_length=50,
                        null=True,
                        verbose_name="Страна",
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("token_verify", models.UUIDField(default=uuid.uuid4, unique=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
