# Generated by Django 5.1.3 on 2024-11-24 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="users/non_avatar.png",
                null=True,
                upload_to="users/%Y",
                verbose_name="Аватар",
            ),
        ),
    ]
