# Generated by Django 5.1.3 on 2024-11-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.SmallIntegerField(verbose_name="Номер столика")),
                ("time", models.DateTimeField(verbose_name="Доступное время")),
                (
                    "restaurant",
                    models.CharField(
                        choices=[("SPB", "Saint-Petersburg"), ("MSK", "Moscow")],
                        max_length=10,
                        verbose_name="Ресторан",
                    ),
                ),
            ],
            options={
                "verbose_name": "Столик",
                "verbose_name_plural": "Столики",
            },
        ),
    ]
