# Generated by Django 5.1.3 on 2024-12-02 23:03

import django.utils.timezone
import reservations.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HistoryReservations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Время создания"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        default="Ожидаем вас",
                        max_length=150,
                        null=True,
                        verbose_name="статус",
                    ),
                ),
            ],
            options={
                "verbose_name": "История резервирования",
                "verbose_name_plural": "История резервирования",
                "ordering": ["-create_at"],
            },
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_table",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="id предыдущего стола"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=20,
                        validators=[reservations.validators.phone_number],
                        verbose_name="Телефон",
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="Комментарий"),
                ),
                (
                    "amount",
                    models.IntegerField(
                        default=500,
                        validators=[reservations.validators.check_amount],
                        verbose_name="Депозит",
                    ),
                ),
                (
                    "create_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Время создания"
                    ),
                ),
                (
                    "is_confirmed",
                    models.BooleanField(
                        default=False, verbose_name="Подтвержденная бронь"
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="Сессия"
                    ),
                ),
                (
                    "link",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Cсылка на оплату",
                    ),
                ),
            ],
            options={
                "verbose_name": "Бронь",
                "verbose_name_plural": "Брони",
            },
        ),
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.SmallIntegerField(verbose_name="Номер столика")),
                (
                    "is_datetime",
                    models.DateTimeField(blank=True, null=True, verbose_name="Время"),
                ),
                (
                    "places",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="Вместимость"
                    ),
                ),
                (
                    "available",
                    models.BooleanField(default=True, verbose_name="Доступность"),
                ),
            ],
            options={
                "verbose_name": "Столик",
                "verbose_name_plural": "Столики",
                "ordering": ["restaurant", "number", "is_datetime"],
            },
        ),
    ]
