# Generated by Django 5.1.3 on 2024-11-29 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0002_table_date_alter_table_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="table",
            name="date",
            field=models.DateField(verbose_name="Доступная дата"),
        ),
        migrations.AlterField(
            model_name="table",
            name="time",
            field=models.TimeField(verbose_name="Доступное время"),
        ),
    ]
