# Generated by Django 5.1.3 on 2024-11-29 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0003_alter_table_date_alter_table_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="table",
            name="date",
        ),
        migrations.RemoveField(
            model_name="table",
            name="time",
        ),
    ]
