# Generated by Django 5.1.3 on 2024-11-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0004_remove_table_date_remove_table_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="table",
            name="date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Доступная дата"
            ),
        ),
        migrations.AddField(
            model_name="table",
            name="time",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Доступное время"
            ),
        ),
    ]
