# Generated by Django 5.1.3 on 2024-11-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0005_table_date_table_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="table",
            name="available",
            field=models.BooleanField(default=True, verbose_name="Доступен"),
        ),
        migrations.AlterField(
            model_name="table",
            name="date",
            field=models.DateField(blank=True, null=True, verbose_name="Дата"),
        ),
        migrations.AlterField(
            model_name="table",
            name="time",
            field=models.TimeField(blank=True, null=True, verbose_name="Время"),
        ),
    ]
