# Generated by Django 5.1.3 on 2024-11-29 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0007_alter_table_date_alter_table_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="table",
            name="places",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
