# Generated by Django 5.1.3 on 2024-11-29 18:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0010_reservation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="create_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 11, 29, 21, 58, 52, 230844),
                verbose_name="Время создания",
            ),
        ),
        migrations.AlterField(
            model_name="table",
            name="available",
            field=models.BooleanField(default=True, verbose_name="Доступность"),
        ),
    ]
