# Generated by Django 5.1.3 on 2024-11-29 19:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0011_alter_reservation_create_at_alter_table_available"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="create_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 11, 29, 22, 8, 31, 721211),
                verbose_name="Время создания",
            ),
        ),
    ]
