# Generated by Django 5.1.3 on 2024-11-29 19:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0012_alter_reservation_create_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="create_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 11, 29, 22, 27, 46, 409684),
                verbose_name="Время создания",
            ),
        ),
    ]
