# Generated by Django 5.1.3 on 2024-11-30 12:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0013_alter_reservation_create_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="table",
            name="date",
        ),
        migrations.RemoveField(
            model_name="table",
            name="time",
        ),
        migrations.AddField(
            model_name="table",
            name="datetime",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Время"),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="create_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 11, 30, 15, 50, 26, 708786),
                verbose_name="Время создания",
            ),
        ),
    ]
