# Generated by Django 5.1.3 on 2024-11-30 12:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "reservations",
            "0014_remove_table_date_remove_table_time_table_datetime_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="table",
            name="datetime",
        ),
        migrations.AddField(
            model_name="table",
            name="date",
            field=models.DateField(blank=True, null=True, verbose_name="Дата"),
        ),
        migrations.AddField(
            model_name="table",
            name="time",
            field=models.TimeField(blank=True, null=True, verbose_name="Время"),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="create_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 11, 30, 15, 51, 33, 325112),
                verbose_name="Время создания",
            ),
        ),
    ]
