# Generated by Django 5.1.3 on 2024-11-29 23:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "reservations",
            "0016_remove_table_date_remove_table_time_table_datetime_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="create_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 11, 30, 2, 19, 13, 698506),
                verbose_name="Время создания",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="is_confirmed",
            field=models.BooleanField(
                default=False, verbose_name="Подтвержденная бронь"
            ),
        ),
    ]
