# Generated by Django 5.1.3 on 2024-12-01 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0017_alter_reservation_create_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="old_table",
            field=models.IntegerField(
                blank=True,
                default=False,
                null=True,
                verbose_name="id предыдущего стола",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="create_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 12, 1, 16, 12, 31, 121009),
                verbose_name="Время создания",
            ),
        ),
    ]
