# Generated by Django 5.1.3 on 2024-12-01 17:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0023_alter_reservation_create_at_alter_table_restaurant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="create_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 12, 1, 20, 44, 34, 313054),
                verbose_name="Время создания",
            ),
        ),
        migrations.AlterField(
            model_name="table",
            name="restaurant",
            field=models.CharField(
                choices=[("SPB", "Saint-Petersburg"), ("MSK", "Moscow")],
                max_length=10,
                verbose_name="Ресторан",
            ),
        ),
    ]
