# Generated by Django 5.1.3 on 2024-12-01 22:01

import datetime
import django.db.models.deletion
import reservations.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0026_alter_table_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="create_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 12, 2, 1, 1, 27, 622941),
                verbose_name="Время создания",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="phone",
            field=models.CharField(
                max_length=20,
                validators=[reservations.validators.phone_number],
                verbose_name="Телефон",
            ),
        ),
        migrations.CreateModel(
            name="HistoryReservations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_at",
                    models.DateTimeField(
                        default=datetime.datetime(2024, 12, 2, 1, 1, 27, 623264),
                        verbose_name="Время создания",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        default="Ожидаем вас",
                        max_length=15,
                        null=True,
                        verbose_name="статус",
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reservations.table",
                        verbose_name="Стол",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
        ),
    ]
