# Generated by Django 5.1.3 on 2024-12-01 22:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "reservations",
            "0027_alter_reservation_create_at_alter_reservation_phone_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historyreservations",
            options={
                "verbose_name": "История резервирования",
                "verbose_name_plural": "История резервирования",
            },
        ),
        migrations.AlterField(
            model_name="historyreservations",
            name="create_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 12, 2, 1, 8, 10, 732613),
                verbose_name="Время создания",
            ),
        ),
        migrations.AlterField(
            model_name="historyreservations",
            name="status",
            field=models.CharField(
                blank=True,
                default="Ожидаем вас",
                max_length=50,
                null=True,
                verbose_name="статус",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="create_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 12, 2, 1, 8, 10, 732290),
                verbose_name="Время создания",
            ),
        ),
    ]
