# Generated by Django 5.1.3 on 2024-12-01 22:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0028_alter_historyreservations_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historyreservations",
            name="create_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 12, 2, 1, 8, 33, 691672),
                verbose_name="Время создания",
            ),
        ),
        migrations.AlterField(
            model_name="historyreservations",
            name="status",
            field=models.CharField(
                blank=True,
                default="Ожидаем вас",
                max_length=150,
                null=True,
                verbose_name="статус",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="create_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 12, 2, 1, 8, 33, 691343),
                verbose_name="Время создания",
            ),
        ),
    ]
