# Generated by Django 5.1.3 on 2024-12-01 22:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0029_alter_historyreservations_create_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historyreservations",
            options={
                "ordering": ["create_at"],
                "verbose_name": "История резервирования",
                "verbose_name_plural": "История резервирования",
            },
        ),
        migrations.AlterField(
            model_name="historyreservations",
            name="create_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 12, 2, 1, 42, 1, 840852),
                verbose_name="Время создания",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="create_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 12, 2, 1, 42, 1, 840536),
                verbose_name="Время создания",
            ),
        ),
    ]
