# Generated by Django 5.1.3 on 2024-12-01 23:43

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0030_alter_historyreservations_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historyreservations",
            options={
                "ordering": ["-create_at"],
                "verbose_name": "История резервирования",
                "verbose_name_plural": "История резервирования",
            },
        ),
        migrations.AlterField(
            model_name="historyreservations",
            name="create_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 12, 2, 2, 43, 17, 840155),
                verbose_name="Время создания",
            ),
        ),
        migrations.AlterField(
            model_name="historyreservations",
            name="table",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="reservations.table",
                verbose_name="Стол",
            ),
        ),
        migrations.AlterField(
            model_name="historyreservations",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="create_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 12, 2, 2, 43, 17, 839840),
                verbose_name="Время создания",
            ),
        ),
    ]
