# Generated by Django 5.1.3 on 2024-12-01 23:56

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0031_alter_historyreservations_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historyreservations",
            name="table",
        ),
        migrations.AlterField(
            model_name="historyreservations",
            name="create_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 12, 2, 2, 56, 58, 691320),
                verbose_name="Время создания",
            ),
        ),
        migrations.AlterField(
            model_name="historyreservations",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="create_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 12, 2, 2, 56, 58, 691017),
                verbose_name="Время создания",
            ),
        ),
    ]
