# Generated by Django 5.1.3 on 2024-12-02 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0032_remove_historyreservations_table_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historyreservations",
            name="create_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 12, 2, 16, 27, 22, 715656),
                verbose_name="Время создания",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="create_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 12, 2, 16, 27, 22, 715356),
                verbose_name="Время создания",
            ),
        ),
    ]
