# Generated by Django 5.1.3 on 2024-12-02 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0034_alter_historyreservations_create_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historyreservations",
            name="create_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 12, 2, 14, 36, 0, 97507, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Время создания",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="create_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 12, 2, 14, 36, 0, 97171, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Время создания",
            ),
        ),
    ]
