# Generated by Django 5.1.3 on 2024-12-02 14:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0035_alter_historyreservations_create_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historyreservations",
            name="create_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Время создания"
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="create_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Время создания"
            ),
        ),
    ]
