# Generated by Django 5.1.3 on 2024-11-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0002_alter_staffrestaurant_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffrestaurant",
            name="photo",
            field=models.ImageField(
                blank=True,
                default="users/non_avatar.png",
                null=True,
                upload_to="staff/<django.db.models.fields.CharField>",
                verbose_name="Фото",
            ),
        ),
    ]
