# Generated by Django 5.1.3 on 2024-11-26 13:48

import restaurant.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0004_alter_staffrestaurant_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffrestaurant",
            name="photo",
            field=models.ImageField(
                blank=True,
                default="non_avatar.png",
                null=True,
                upload_to=restaurant.models.upload,
                verbose_name="Фото",
            ),
        ),
    ]
