# Generated by Django 5.1.3 on 2024-11-26 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0005_alter_staffrestaurant_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="missionsrestaurant",
            name="position",
            field=models.SmallIntegerField(
                blank=True, null=True, verbose_name="Позиция"
            ),
        ),
    ]
