# Generated by Django 5.1.3 on 2024-11-26 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0006_missionsrestaurant_position"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="missionsrestaurant",
            name="position",
        ),
        migrations.AddField(
            model_name="missionsrestaurant",
            name="serial_number",
            field=models.SmallIntegerField(
                blank=True, null=True, verbose_name="Порядковый номер"
            ),
        ),
    ]
