# Generated by Django 5.1.3 on 2024-11-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0009_alter_staffrestaurant_date_employment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Description",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=100, verbose_name="Описание ресторана"),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        default=False, verbose_name="Признак текущей версии"
                    ),
                ),
            ],
            options={
                "verbose_name": "Версия",
                "verbose_name_plural": "Версии",
            },
        ),
    ]
