# Generated by Django 5.1.3 on 2024-11-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0010_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="description",
            options={
                "verbose_name": "Описание ресторана",
                "verbose_name_plural": "Описания ресторана",
            },
        ),
        migrations.AlterField(
            model_name="description",
            name="description",
            field=models.TextField(verbose_name="Описание ресторана"),
        ),
    ]
