# Generated by Django 5.1.3 on 2024-11-28 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0011_alter_description_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Services",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service",
                    models.CharField(max_length=100, verbose_name="Услуга ресторана"),
                ),
            ],
            options={
                "verbose_name": "Услуга",
                "verbose_name_plural": "Услуги",
            },
        ),
    ]
