# Generated by Django 5.1.3 on 2024-11-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0014_contacts"),
    ]

    operations = [
        migrations.AddField(
            model_name="contacts",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="Признак публикации"),
        ),
        migrations.AlterField(
            model_name="description",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="Признак публикации"),
        ),
        migrations.AlterField(
            model_name="services",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="Признак публикации"),
        ),
    ]
