# Generated by Django 5.1.3 on 2024-11-28 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "restaurant",
            "0015_contacts_is_published_alter_description_is_published_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="contacts",
            name="extra",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Дополнительная информация",
            ),
        ),
        migrations.AlterField(
            model_name="contacts",
            name="phone",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="Номер телефона"
            ),
        ),
    ]
