# Generated by Django 5.1.3 on 2024-11-28 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0018_alter_description_background"),
    ]

    operations = [
        migrations.AlterField(
            model_name="description",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Описание ресторана"
            ),
        ),
    ]
