# Generated by Django 5.1.3 on 2024-12-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0019_alter_description_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Название")),
                ("city", models.CharField(max_length=150, verbose_name="Город")),
            ],
            options={
                "verbose_name": "Ресторан",
                "verbose_name_plural": "Рестораны",
            },
        ),
    ]
