# Generated by Django 5.1.3 on 2024-12-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0020_restaurant"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="tables_count",
            field=models.SmallIntegerField(
                default=10, verbose_name="Количество столов"
            ),
        ),
    ]
