# Generated by Django 5.1.3 on 2024-12-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0021_restaurant_tables_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="scheme_tables",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="Схема столов"
            ),
        ),
    ]
