# Generated by Django 5.1.3 on 2024-12-02 15:45

import restaurant.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0022_restaurant_scheme_tables"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="scheme_tables",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=restaurant.models.upload,
                verbose_name="Фото",
            ),
        ),
    ]
